name: CI DevOps 2024

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      # Checkout your GitHub code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Navigate to the `simple-api` directory and build with Maven
      - name: Build and test with Maven
        run: |
          cd simple-api
          mvn clean verify

  build-and-push-docker-image:
    needs: test-backend # Run only if the test-backend job passes
    runs-on: ubuntu-22.04

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Login to DockerHub
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push backend image
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push database image
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database # Replace with the relative path to the database Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      # Build and push HTTPd image
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./httpd # Replace with the relative path to the httpd Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/main' }}
